- name: ":robot: bot"
  color: "69cde9"
  description: ""
- name: ":bug: bug"
  color: "b60205"
  description: ""
- name: ":game_die: dependencies"
  color: "0366d6"
  description: ""
- name: ":memo: documentation"
  color: "c5def5"
  description: ""
- name: ":busts_in_silhouette: duplicate"
  color: "cccccc"
  description: ""
- name: ":sparkles: enhancement"
  color: "0054ca"
  description: ""
- name: ":bulb: feature request"
  color: "0e8a16"
  description: ""
- name: ":mega: feedback"
  color: "03a9f4"
  description: ""
- name: ":rocket: future maybe"
  color: "fef2c0"
  description: ""
- name: ":hatching_chick: good first issue"
  color: "7057ff"
  description: ""
- name: ":pray: help wanted"
  color: "4caf50"
  description: ""
- name: ":hand: hold"
  color: "24292f"
  description: ""
- name: ":no_entry_sign: invalid"
  color: "e6e6e6"
  description: ""
- name: ":interrobang: maybe bug"
  color: "ff5722"
  description: ""
- name: ":thinking: needs more info"
  color: "795548"
  description: ""
- name: ":question: question"
  color: "3f51b5"
  description: ""
- name: ":coffin: wontfix"
  color: "ffffff"
  description: ""
