- name: "Status: 🗯️ Waiting for feedback"
  color: "f7d692"
- name: "Status: 🔴 Blocked"
  color: "f7d692"
  description: "Blocked by another issue or pull request"
- name: "Status: 📌 Before next release"
  color: "f7d692"
  description: "Has to be done before the next release"
- name: "Status: 🔒 After next release"
  color: "f7d692"
  description: "Will be done after the next release"
- name: "Status: 🟡 Nearly resolved"
  color: "f7d692"
  description: "This might be resolved or is about to be resolved"

- name: "Closed: ⚰️ Inactive"
  color: "959a9c"
  description: "No answer was received for weeks"
- name: "Closed: 👥 Duplicate"
  color: "959a9c"
  description: "Issue duplicates an existing issue"
- name: "Closed: 🗑️ Bad issue"
  color: "959a9c"
- name: "Closed: ☠️ cannot be done"
  color: "959a9c"

- name: "Priority: 🚨 Urgent"
  color: "03adfc"
- name: "Priority: 💤 Low priority"
  color: "03adfc"

- name: "Complexity: ☣️ Hard to do"
  color: "ff9efc"
- name: "Complexity: 🟩 Easy to do"
  color: "ff9efc"

- name: "Popularity: ❤️‍🔥 extreme"
  color: "ffc7ea"
- name: "Popularity: ❤️ high"
  color: "ffc7ea"

# VPN providers
- name: "☁️ AirVPN"
  color: "cfe8d4"
- name: "☁️ Custom"
  color: "cfe8d4"
- name: "☁️ Cyberghost"
  color: "cfe8d4"
- name: "☁️ Giganews"
  color: "cfe8d4"
- name: "☁️ HideMyAss"
  color: "cfe8d4"
- name: "☁️ IPVanish"
  color: "cfe8d4"
- name: "☁️ IVPN"
  color: "cfe8d4"
- name: "☁️ ExpressVPN"
  color: "cfe8d4"
- name: "☁️ FastestVPN"
  color: "cfe8d4"
- name: "☁️ Mullvad"
  color: "cfe8d4"
- name: "☁️ NordVPN"
  color: "cfe8d4"
- name: "☁️ Perfect Privacy"
  color: "cfe8d4"
- name: "☁️ PIA"
  color: "cfe8d4"
- name: "☁️ Privado"
  color: "cfe8d4"
- name: "☁️ PrivateVPN"
  color: "cfe8d4"
- name: "☁️ ProtonVPN"
  color: "cfe8d4"
- name: "☁️ PureVPN"
  color: "cfe8d4"
- name: "☁️ SlickVPN"
  color: "cfe8d4"
- name: "☁️ Surfshark"
  color: "cfe8d4"
- name: "☁️ Torguard"
  color: "cfe8d4"
- name: "☁️ VPNSecure.me"
  color: "cfe8d4"
- name: "☁️ VPNUnlimited"
  color: "cfe8d4"
- name: "☁️ Vyprvpn"
  color: "cfe8d4"
- name: "☁️ WeVPN"
  color: "cfe8d4"
- name: "☁️ Windscribe"
  color: "cfe8d4"

- name: "Category: User error 🤦"
  from_name: "Category: Config problem 📝"
  color: "ffc7ea"
- name: "Category: Healthcheck 🩺"
  color: "ffc7ea"
- name: "Category: Documentation ✒️"
  description: "A problem with the readme or a code comment."
  color: "ffc7ea"
- name: "Category: Maintenance ⛓️"
  description: "Anything related to code or other maintenance"
  color: "ffc7ea"
- name: "Category: Logs 📚"
  description: "Something to change in logs"
  color: "ffc7ea"
- name: "Category: Good idea 🎯"
  description: "This is a good idea, judged by the maintainers"
  color: "ffc7ea"
- name: "Category: Motivated! 🙌"
  description: "Your pumpness makes me pumped! The issue or PR shows great motivation!"
  color: "ffc7ea"
- name: "Category: Foolproof settings 👼"
  color: "ffc7ea"
- name: "Category: Label missing ❗"
  color: "ffc7ea"
- name: "Category: updater ♻️"
  color: "ffc7ea"
  description: "Concerns the code to update servers data"
- name: "Category: New provider 🆕"
  color: "ffc7ea"
- name: "Category: OpenVPN 🔐"
  color: "ffc7ea"
- name: "Category: Wireguard 🔐"
  color: "ffc7ea"
- name: "Category: DNS 📠"
  color: "ffc7ea"
- name: "Category: Firewall ⛓️"
  color: "ffc7ea"
- name: "Category: Routing 🛤️"
  color: "ffc7ea"
- name: "Category: IPv6 🛰️"
  color: "ffc7ea"
- name: "Category: VPN port forwarding 📥"
  color: "ffc7ea"
- name: "Category: HTTP proxy 🔁"
  color: "ffc7ea"
- name: "Category: Shadowsocks 🔁"
  color: "ffc7ea"
- name: "Category: control server ⚙️"
  color: "ffc7ea"
- name: "Category: kernel 🧠"
  color: "ffc7ea"
- name: "Category: public IP service 💬"
  color: "ffc7ea"
- name: "Category: servers storage 📦"
  color: "ffc7ea"
- name: "Category: Performance 🚀"
  color: "ffc7ea"
- name: "Category: Investigation 🔍"
  color: "ffc7ea"
