- name: "Bug :bug:"
  color: "b60205"
  description: ""
- name: "Feature request :bulb:"
  color: "0e8a16"
  description: ""
- name: "Help wanted :pray:"
  color: "4caf50"
  description: ""
- name: "Documentation :memo:"
  color: "c5def5"
  description: ""
- name: "Needs more info :thinking:"
  color: "795548"
  description: ""

# Priority
- name: "🚨 Urgent"
  color: "d5232f"
  description: ""
- name: "💤 Low priority"
  color: "4285f4"
  description: ""

# VPN providers
- name: ":cloud: Cyberghost"
  color: "cfe8d4"
  description: ""
- name: ":cloud: HideMyAss"
  color: "cfe8d4"
  description: ""
- name: ":cloud: IPVanish"
  color: "cfe8d4"
  description: ""
- name: ":cloud: IVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: ExpressVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: FastestVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: Mullvad"
  color: "cfe8d4"
  description: ""
- name: ":cloud: NordVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: Perfect Privacy"
  color: "cfe8d4"
  description: ""
- name: ":cloud: PIA"
  color: "cfe8d4"
  description: ""
- name: ":cloud: Privado"
  color: "cfe8d4"
  description: ""
- name: ":cloud: PrivateVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: ProtonVPN"
  color: "cfe8d4"
- name: ":cloud: PureVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: SlickVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: Surfshark"
  color: "cfe8d4"
  description: ""
- name: ":cloud: Torguard"
  color: "cfe8d4"
  description: ""
- name: ":cloud: VPNUnlimited"
  color: "cfe8d4"
  description: ""
- name: ":cloud: Vyprvpn"
  color: "cfe8d4"
  description: ""
- name: ":cloud: WeVPN"
  color: "cfe8d4"
  description: ""
- name: ":cloud: Windscribe"
  color: "cfe8d4"
  description: ""

# Problem category
- name: "Openvpn"
  color: "ffc7ea"
  description: ""
- name: "Wireguard"
  color: "ffc7ea"
  description: ""
- name: "Unbound (DNS over TLS)"
  color: "ffc7ea"
  description: ""
- name: "Firewall"
  color: "ffc7ea"
  description: ""
- name: "HTTP proxy"
  color: "ffc7ea"
  description: ""
- name: "Shadowsocks"
  color: "ffc7ea"
  description: ""
- name: "Healthcheck server"
  color: "ffc7ea"
  description: ""
- name: "Control server"
  color: "ffc7ea"
  description: ""
