package updater

import (
	"github.com/qdm12/gluetun/internal/models"
)

func hardcodedServers() (servers []models.Server) {
	return []models.Server{
		{Country: "Albania", Hostname: "albania-ca-version-2.expressnetw.com"},
		{Country: "Algeria", Hostname: "algeria-ca-version-2.expressnetw.com"},
		{Country: "Andorra", Hostname: "andorra-ca-version-2.expressnetw.com"},
		{Country: "Argentina", Hostname: "argentina-ca-version-2.expressnetw.com"},
		{Country: "Armenia", Hostname: "armenia-ca-version-2.expressnetw.com"},
		{Country: "Australia", City: "Adelaide", Hostname: "australia-adelaide--ca-version-2.expressnetw.com"},
		{Country: "Australia", City: "Brisbane", Hostname: "australia-brisbane-ca-version-2.expressnetw.com"},
		{Country: "Australia", City: "Melbourne", Hostname: "australia-melbourne-ca-version-2.expressnetw.com"},
		{Country: "Australia", City: "Perth", Hostname: "australia-perth-ca-version-2.expressnetw.com"},
		{Country: "Australia", City: "Sydney", Hostname: "australia-sydney-2-ca-version-2.expressnetw.com"},
		{Country: "Australia", City: "Sydney", Hostname: "australia-sydney-ca-version-2.expressnetw.com"},
		{Country: "Australia", City: "Woolloomooloo", Hostname: "australia-woolloomooloo-2-ca-version-2.expressnetw.com"},
		{Country: "Austria", Hostname: "austria-ca-version-2.expressnetw.com"},
		{Country: "Azerbaijan", Hostname: "azerbaijan-ca-version-2.expressnetw.com"},
		{Country: "Bahamas", Hostname: "bahamas-ca-version-2.expressnetw.com"},
		{Country: "Bangladesh", Hostname: "bangladesh-ca-version-2.expressnetw.com"},
		{Country: "Belarus", Hostname: "belarus-ca-version-2.expressnetw.com"},
		{Country: "Belgium", Hostname: "belgium-ca-version-2.expressnetw.com"},
		{Country: "Bermuda", Hostname: "bermuda-ca-version-2.expressnetw.com"},
		{Country: "Bhutan", Hostname: "bhutan-ca-version-2.expressnetw.com"},
		{Country: "Bolivia", Hostname: "bolivia-ca-version-2.expressnetw.com"},
		{Country: "Bosnia and Herzegovina", Hostname: "bosniaandherzegovina-ca-version-2.expressnetw.com"},
		{Country: "Brazil", Hostname: "brazil-2-ca-version-2.expressnetw.com"},
		{Country: "Brazil", Hostname: "brazil-ca-version-2.expressnetw.com"},
		{Country: "Brunei", Hostname: "brunei-ca-version-2.expressnetw.com"},
		{Country: "Bulgaria", Hostname: "bulgaria-ca-version-2.expressnetw.com"},
		{Country: "Cambodia", Hostname: "cambodia-ca-version-2.expressnetw.com"},
		{Country: "Canada", City: "Montreal", Hostname: "canada-montreal-ca-version-2.expressnetw.com"},
		{Country: "Canada", City: "Toronto", Hostname: "canada-toronto-2-ca-version-2.expressnetw.com"},
		{Country: "Canada", City: "Toronto", Hostname: "canada-toronto-ca-version-2.expressnetw.com"},
		{Country: "Cayman Islands", Hostname: "caymanislands-ca-version-2.expressnetw.com"},
		{Country: "Chile", Hostname: "chile-ca-version-2.expressnetw.com"},
		{Country: "Colombia", Hostname: "colombia-ca-version-2.expressnetw.com"},
		{Country: "Costa Rica", Hostname: "costarica-ca-version-2.expressnetw.com"},
		{Country: "Croatia", Hostname: "croatia-ca-version-2.expressnetw.com"},
		{Country: "Cuba", Hostname: "cuba-ca-version-2.expressnetw.com"},
		{Country: "Cyprus", Hostname: "cyprus-ca-version-2.expressnetw.com"},
		{Country: "Czech Republic", Hostname: "czechrepublic-ca-version-2.expressnetw.com"},
		{Country: "Denmark", Hostname: "denmark-ca-version-2.expressnetw.com"},
		{Country: "Dominican Republic", Hostname: "dominicanrepublic-ca-version-2.expressnetw.com"},
		{Country: "Ecuador", Hostname: "ecuador-ca-version-2.expressnetw.com"},
		{Country: "Egypt", Hostname: "egypt-ca-version-2.expressnetw.com"},
		{Country: "Estonia", Hostname: "estonia-ca-version-2.expressnetw.com"},
		{Country: "Finland", Hostname: "finland-ca-version-2.expressnetw.com"},
		{Country: "France", City: "Alsace", Hostname: "france-alsace-ca-version-2.expressnetw.com"},
		{Country: "France", City: "Marseille", Hostname: "france-marseille-ca-version-2.expressnetw.com"},
		{Country: "France", City: "Paris", Hostname: "france-paris-1-ca-version-2.expressnetw.com"},
		{Country: "France", City: "Paris", Hostname: "france-paris-2-ca-version-2.expressnetw.com"},
		{Country: "France", City: "Strasbourg", Hostname: "france-strasbourg-ca-version-2.expressnetw.com"},
		{Country: "Georgia", Hostname: "georgia-ca-version-2.expressnetw.com"},
		{Country: "Germany", City: "Frankfurt", Hostname: "germany-darmstadt-ca-version-2.expressnetw.com"},
		{Country: "Germany", City: "Frankfurt", Hostname: "germany-frankfurt-1-ca-version-2.expressnetw.com"},
		{Country: "Germany", City: "Nuremberg", Hostname: "germany-nuremberg-ca-version-2.expressnetw.com"},
		{Country: "Ghana", Hostname: "ghana-ca-version-2.expressnetw.com"},
		{Country: "Greece", Hostname: "greece-ca-version-2.expressnetw.com"},
		{Country: "Guam", Hostname: "guam-ca-version-2.expressnetw.com"},
		{Country: "Guatemala", Hostname: "guatemala-ca-version-2.expressnetw.com"},
		{Country: "Honduras", Hostname: "honduras-ca-version-2.expressnetw.com"},
		{Country: "Hong Kong", Hostname: "hongkong-1-ca-version-2.expressnetw.com"},
		{Country: "Hong Kong", Hostname: "hongkong-2-ca-version-2.expressnetw.com"},
		{Country: "Hungary", Hostname: "hungary-ca-version-2.expressnetw.com"},
		{Country: "Iceland", Hostname: "iceland-ca-version-2.expressnetw.com"},
		{Country: "India (via Singapore)", Hostname: "india-sg-ca-version-2.expressnetw.com"},
		{Country: "India (via UK)", Hostname: "india-uk-ca-version-2.expressnetw.com"},
		{Country: "Indonesia", Hostname: "indonesia-ca-version-2.expressnetw.com"},
		{Country: "Ireland", Hostname: "ireland-ca-version-2.expressnetw.com"},
		{Country: "Isle of Man", Hostname: "isleofman-ca-version-2.expressnetw.com"},
		{Country: "Israel", Hostname: "israel-ca-version-2.expressnetw.com"},
		{Country: "Italy", City: "Cosenza", Hostname: "italy-cosenza-ca-version-2.expressnetw.com"},
		{Country: "Italy", City: "Milan", Hostname: "italy-milan-ca-version-2.expressnetw.com"},
		{Country: "Italy", City: "Naples", Hostname: "italy-naples-ca-version-2.expressnetw.com"},
		{Country: "Jamaica", Hostname: "jamaica-ca-version-2.expressnetw.com"},
		{Country: "Japan", City: "Osaka", Hostname: "japan-osaka-ca-version-2.expressnetw.com"},
		{Country: "Japan", City: "Shibuya", Hostname: "japan-shibuya-ca-version-2.expressnetw.com"},
		{Country: "Japan", City: "Tokyo", Hostname: "japan-tokyo-ca-version-2.expressnetw.com"},
		{Country: "Japan", City: "Yokohama", Hostname: "japan-yokohama-ca-version-2.expressnetw.com"},
		{Country: "Jersey", Hostname: "jersey-ca-version-2.expressnetw.com"},
		{Country: "Kazakhstan", Hostname: "kazakhstan-ca-version-2.expressnetw.com"},
		{Country: "Kenya", Hostname: "kenya-ca-version-2.expressnetw.com"},
		{Country: "Laos", Hostname: "laos-ca-version-2.expressnetw.com"},
		{Country: "Latvia", Hostname: "latvia-ca-version-2.expressnetw.com"},
		{Country: "Lebanon", Hostname: "lebanon-ca-version-2.expressnetw.com"},
		{Country: "Liechtenstein", Hostname: "liechtenstein-ca-version-2.expressnetw.com"},
		{Country: "Lithuania", Hostname: "lithuania-ca-version-2.expressnetw.com"},
		{Country: "Luxembourg", Hostname: "luxembourg-ca-version-2.expressnetw.com"},
		{Country: "Macau", Hostname: "macau-ca-version-2.expressnetw.com"},
		{Country: "Malaysia", Hostname: "malaysia-ca-version-2.expressnetw.com"},
		{Country: "Malta", Hostname: "malta-ca-version-2.expressnetw.com"},
		{Country: "Mexico", Hostname: "mexico-ca-version-2.expressnetw.com"},
		{Country: "Moldova", Hostname: "moldova-ca-version-2.expressnetw.com"},
		{Country: "Monaco", Hostname: "monaco-ca-version-2.expressnetw.com"},
		{Country: "Mongolia", Hostname: "mongolia-ca-version-2.expressnetw.com"},
		{Country: "Montenegro", Hostname: "montenegro-ca-version-2.expressnetw.com"},
		{Country: "Morocco", Hostname: "morocco-ca-version-2.expressnetw.com"},
		{Country: "Myanmar", Hostname: "myanmar-ca-version-2.expressnetw.com"},
		{Country: "Nepal", Hostname: "nepal-ca-version-2.expressnetw.com"},
		{Country: "Netherlands", City: "Amsterdam", Hostname: "netherlands-amsterdam-ca-version-2.expressnetw.com"},
		{Country: "Netherlands", City: "Rotterdam", Hostname: "netherlands-rotterdam-ca-version-2.expressnetw.com"},
		{Country: "Netherlands", City: "The Hague", Hostname: "netherlands-thehague-ca-version-2.expressnetw.com"},
		{Country: "New Zealand", Hostname: "newzealand-ca-version-2.expressnetw.com"},
		{Country: "North Macedonia", Hostname: "macedonia-ca-version-2.expressnetw.com"},
		{Country: "Norway", Hostname: "norway-ca-version-2.expressnetw.com"},
		{Country: "Pakistan", Hostname: "pakistan-ca-version-2.expressnetw.com"},
		{Country: "Panama", Hostname: "panama-ca-version-2.expressnetw.com"},
		{Country: "Peru", Hostname: "peru-ca-version-2.expressnetw.com"},
		{Country: "Philippines (via Singapore)", Hostname: "ph-via-sing-ca-version-2.expressnetw.com"},
		{Country: "Poland", Hostname: "poland-ca-version-2.expressnetw.com"},
		{Country: "Portugal", Hostname: "portugal-ca-version-2.expressnetw.com"},
		{Country: "Puerto Rico", Hostname: "puertorico-ca-version-2.expressnetw.com"},
		{Country: "Romania", Hostname: "romania-ca-version-2.expressnetw.com"},
		{Country: "Serbia", Hostname: "serbia-ca-version-2.expressnetw.com"},
		{Country: "Singapore", City: "CBD", Hostname: "singapore-cbd-ca-version-2.expressnetw.com"},
		{Country: "Singapore", City: "Jurong", Hostname: "singapore-jurong-ca-version-2.expressnetw.com"},
		{Country: "Singapore", City: "Marina Bay", Hostname: "singapore-marinabay-ca-version-2.expressnetw.com"},
		{Country: "Slovakia", Hostname: "slovakia-ca-version-2.expressnetw.com"},
		{Country: "Slovenia", Hostname: "slovenia-ca-version-2.expressnetw.com"},
		{Country: "South Africa", Hostname: "southafrica-ca-version-2.expressnetw.com"},
		{Country: "South Korea", Hostname: "southkorea2-ca-version-2.expressnetw.com"},
		{Country: "Spain", City: "Barcelona", Hostname: "spain-barcelona-ca-version-2.expressnetw.com"},
		{Country: "Spain", City: "Barcelona", Hostname: "spain-barcelona2-ca-version-2.expressnetw.com"},
		{Country: "Spain", City: "Madrid", Hostname: "spain-ca-version-2.expressnetw.com"},
		{Country: "Sri Lanka", Hostname: "srilanka-ca-version-2.expressnetw.com"},
		{Country: "Sweden", Hostname: "sweden-ca-version-2.expressnetw.com"},
		{Country: "Sweden", Hostname: "sweden2-ca-version-2.expressnetw.com"},
		{Country: "Switzerland", Hostname: "switzerland-2-ca-version-2.expressnetw.com"},
		{Country: "Switzerland", Hostname: "switzerland-ca-version-2.expressnetw.com"},
		{Country: "Taiwan", Hostname: "taiwan-3-ca-version-2.expressnetw.com"},
		{Country: "Thailand", Hostname: "thailand-ca-version-2.expressnetw.com"},
		{Country: "Trinidad and Tobago", Hostname: "trinidadandtobago-ca-version-2.expressnetw.com"},
		{Country: "Turkey", Hostname: "turkey-ca-version-2.expressnetw.com"},
		{Country: "UK", City: "Docklands", Hostname: "uk-1-docklands-ca-version-2.expressnetw.com"},
		{Country: "UK", City: "East London", Hostname: "uk-east-london-ca-version-2.expressnetw.com"},
		{Country: "UK", City: "London", Hostname: "uk-london-ca-version-2.expressnetw.com"},
		{Country: "UK", City: "Midlands", Hostname: "uk-midlands-ca-version-2.expressnetw.com"},
		{Country: "UK", City: "Tottenham", Hostname: "uk-tottenham-ca-version-2.expressnetw.com"},
		{Country: "UK", City: "Wembley", Hostname: "uk-wembley-ca-version-2.expressnetw.com"},
		{Country: "Ukraine", Hostname: "ukraine-ca-version-2.expressnetw.com"},
		{Country: "Uruguay", Hostname: "uruguay-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Albuquerque", Hostname: "usa-albuquerque-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Atlanta", Hostname: "usa-atlanta-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Boston", Hostname: "us-boston-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Chicago", Hostname: "usa-chicago-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Dallas", Hostname: "usa-dallas-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Denver", Hostname: "usa-denver-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Houston", Hostname: "usa-houston-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Jackson", Hostname: "us-jackson-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Lincoln Park", Hostname: "usa-lincolnpark-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Little Rock", Hostname: "us-littlerock-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Los Angeles", Hostname: "usa-losangeles-2-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Los Angeles", Hostname: "usa-losangeles-3-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Los Angeles", Hostname: "usa-losangeles-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Los Angeles", Hostname: "usa-losangeles5-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Miami", Hostname: "usa-miami-2-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Miami", Hostname: "usa-miami-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "New Jersey", Hostname: "usa-newjersey-1-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "New Jersey", Hostname: "usa-newjersey-3-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "New Jersey", Hostname: "usa-newjersey2-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "New Orleans", Hostname: "us-neworleans-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "New York", Hostname: "usa-newyork-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Oklahoma City", Hostname: "us-oklahoma-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Phoenix", Hostname: "usa-phoenix-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Salt Lake City", Hostname: "usa-saltlakecity-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "San Francisco", Hostname: "usa-sanfrancisco-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Santa Monica", Hostname: "usa-santa-monica-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Seattle", Hostname: "usa-seattle-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Tampa", Hostname: "usa-tampa-1-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Washington DC", Hostname: "usa-washingtondc-ca-version-2.expressnetw.com"},
		{Country: "USA", City: "Wichita", Hostname: "us-wichita-ca-version-2.expressnetw.com"},
		{Country: "Uzbekistan", Hostname: "uzbekistan-ca-version-2.expressnetw.com"},
		{Country: "Venezuela", Hostname: "venezuela-ca-version-2.expressnetw.com"},
		{Country: "Vietnam", Hostname: "vietnam-ca-version-2.expressnetw.com"},
	}
}
