linters-settings:
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - maligned
        - goerr113
        - containedctx
    - path: internal/server/
      linters:
        - dupl
    - path: internal/configuration/
      linters:
        - dupl
    - path: internal/constants/
      linters:
        - dupl
    - text: "exported: exported var Err*"
      linters:
        - revive
    - text: "mnd: Magic number: 0644*"
      linters:
        - gomnd
    - text: "mnd: Magic number: 0400*"
      linters:
        - gomnd
    - text: "variable 'mssFix' is only used in the if-statement*"
      path: "openvpnconf.go"
      linters:
        - ifshort
    - text: "variable 'auth' is only used in the if-statement*"
      path: "openvpnconf.go"
      linters:
        - ifshort
    - linters:
        - lll
      source: "^//go:generate "

linters:
  enable:
    # - cyclop
    # - errorlint
    # - ireturn
    # - varnamelen
    # - wrapcheck
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    - execinquery
    - exhaustive
    - exportloopref
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - goprintffuncname
    - gosec
    - grouper
    - ifshort
    - importas
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace

run:
  skip-dirs:
    - .devcontainer
    - .github
    - doc
