package updater

// getAvailableCities get available cities as listed on the WeVPN website.
func getAvailableCities() (cities []string) {
	return []string{
		"Cairo",
		"Chennai",
		"Denizli",
		"Dubai",
		"Johannesburg",
		"Lagos",
		"Tel Aviv",
		"Atlanta",
		"Buenos Aires",
		"Chicago",
		"Dallas",
		"Denver",
		"Los Angeles",
		"Los Angeles-PF",
		"Mexico City",
		"Miami",
		"Montreal",
		"New Jersey",
		"New York",
		"New York-PF",
		"Phoenix",
		"Salt Lake City",
		"San Jose",
		"Sao Paulo",
		"Seattle",
		"Toronto",
		"Vancouver",
		"Washington DC",
		"Auckland",
		"Hanoi",
		"Hong Kong",
		"Jakarta",
		"Manila",
		"Melbourne",
		"Moscow",
		"Seoul",
		"Sibu",
		"Singapore",
		"St Petersburg",
		"Sydney",
		"Taipei",
		"Tokyo",
		"Amsterdam",
		"Athens",
		"Belgrade",
		"Brussels",
		"Bucharest",
		"Budapest",
		"Copenhagen",
		"Dublin",
		"Frankfurt",
		"Helsinki",
		"Kiev",
		"Lisbon",
		"London",
		"London-PF",
		"Luxembourg",
		"Madrid",
		"Manchester",
		"Milan",
		"Oslo",
		"Oulu",
		"Paris",
		"Prague",
		"Sofia",
		"Stockholm",
		"Vienna",
		"Warsaw",
		"Zurich",
	}
}
